#!/usr/bin/env bash
#
# bump_version.sh — single source of truth for bumping the SDK version.
#
# Updates every file that hard-codes the published artifact version so they
# stay in sync. Does NOT touch CHANGELOG.md or spm/Package.swift:
#   - CHANGELOG.md entries should be authored manually as part of the bump.
#   - spm/Package.swift is regenerated by prepare_spm_release.sh during deploy.
#
# Usage:
#   scripts/bump_version.sh <new_version>
# Example:
#   scripts/bump_version.sh 0.3.0
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
GRADLE_PROPERTIES="$ROOT_DIR/gradle.properties"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <new_version>" >&2
  exit 1
fi

NEW_VERSION="$1"

# Loose semver gate: X.Y.Z plus optional pre-release/build suffix.
if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]]; then
  echo "[bump] ERROR: version '$NEW_VERSION' does not look like semver (X.Y.Z)" >&2
  exit 2
fi

CURRENT_VERSION="$(grep '^PUBLISHING_VERSION=' "$GRADLE_PROPERTIES" | cut -d'=' -f2-)"

if [[ -z "$CURRENT_VERSION" ]]; then
  echo "[bump] ERROR: could not read PUBLISHING_VERSION from gradle.properties" >&2
  exit 3
fi

if [[ "$CURRENT_VERSION" == "$NEW_VERSION" ]]; then
  echo "[bump] Nothing to do — gradle.properties is already at $NEW_VERSION"
  exit 0
fi

echo "[bump] $CURRENT_VERSION → $NEW_VERSION"

# Cross-platform in-place sed (BSD sed on macOS needs '' after -i).
sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

# Files where the old version literal must be replaced. Each entry is
# "<file>|<sed-expression>". The sed expression uses ${CURRENT_VERSION} and
# ${NEW_VERSION} so we only touch the right line, not any other coincidence
# (e.g. dependency versions of unrelated libs).
TARGETS=(
  "gradle.properties|s|^PUBLISHING_VERSION=${CURRENT_VERSION}\$|PUBLISHING_VERSION=${NEW_VERSION}|"
  "example-android/build.gradle.kts|s|com\\.deepdots\\.sdk:shared-android:${CURRENT_VERSION}|com.deepdots.sdk:shared-android:${NEW_VERSION}|g"
  "README.md|s|com\\.deepdots\\.sdk:shared-android:${CURRENT_VERSION}|com.deepdots.sdk:shared-android:${NEW_VERSION}|g"
  "README.md|s|DeepdotsSDK-${CURRENT_VERSION}\\.xcframework\\.zip|DeepdotsSDK-${NEW_VERSION}.xcframework.zip|g"
  "README.md|s|version \\\`${CURRENT_VERSION}\\\`|version \\\`${NEW_VERSION}\\\`|g"
  "docs/src/content/docs/installation.mdx|s|com\\.deepdots\\.sdk:shared-android:${CURRENT_VERSION}|com.deepdots.sdk:shared-android:${NEW_VERSION}|g"
  "docs/src/content/docs/da/installation.mdx|s|com\\.deepdots\\.sdk:shared-android:${CURRENT_VERSION}|com.deepdots.sdk:shared-android:${NEW_VERSION}|g"
  "docs/src/content/docs/es/installation.mdx|s|com\\.deepdots\\.sdk:shared-android:${CURRENT_VERSION}|com.deepdots.sdk:shared-android:${NEW_VERSION}|g"
  "docs/src/content/docs/guides/examples.mdx|s|com\\.deepdots\\.sdk:shared-android:${CURRENT_VERSION}|com.deepdots.sdk:shared-android:${NEW_VERSION}|g"
)

CHANGED=()
for entry in "${TARGETS[@]}"; do
  file="${entry%%|*}"
  expr="${entry#*|}"
  path="$ROOT_DIR/$file"
  if [[ ! -f "$path" ]]; then
    echo "[bump] WARN: $file not found, skipping"
    continue
  fi
  before="$(shasum "$path" | awk '{print $1}')"
  sed_inplace "$expr" "$path"
  after="$(shasum "$path" | awk '{print $1}')"
  if [[ "$before" != "$after" ]]; then
    CHANGED+=("$file")
    echo "[bump]   updated $file"
  fi
done

# Sanity: nothing referencing the old version literal should remain in the
# files we edited. Catch stragglers early.
echo "[bump] Scanning for leftover '${CURRENT_VERSION}' references in tracked source/docs..."
LEFTOVERS=$(
  cd "$ROOT_DIR"
  git grep -nFw "$CURRENT_VERSION" \
    -- gradle.properties \
       'example-android/**' \
       'README.md' \
       'docs/src/**' \
    2>/dev/null || true
)
if [[ -n "$LEFTOVERS" ]]; then
  echo "[bump] WARN: the following lines still mention $CURRENT_VERSION — review manually:" >&2
  echo "$LEFTOVERS" >&2
fi

echo
echo "[bump] Done. Files touched: ${#CHANGED[@]}"
echo
echo "Next steps:"
echo "  1. Add a '## $NEW_VERSION' section to CHANGELOG.md"
echo "  2. Review with: git diff"
echo "  3. Commit + tag:"
echo "       git add -A && git commit -m 'Bump version to $NEW_VERSION'"
echo "       git tag -a $NEW_VERSION -m 'Release $NEW_VERSION'"
echo "  4. Build & deploy:"
echo "       ./scripts/deploy_sdk_release.sh"
